# Generated by Django 5.1.4 on 2025-01-10 20:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, default='uploads/no-img.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
